### ISSUE TITLE
encounter missing install target

### ISSUE THREAD

**Issue by AlucardNosferatu** [opencog/cogserver#13]
try to build cogserver follow the procedures written in readme.md:
scrooge@scrooge-X455LD:~/cogserver/build$ cmake ..
-- Build type: Release
-- CogUtil found.
-- AtomSpace found.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Boost version 105800 found.
-- Guile (2.2.3 >= 2.2.2) was found.
-- Python 3.5.2 interpreter found.
-- Python 3.5.2 libraries found.
-- Cython ( 0.23.5 >= 0.23.0) found.
-- Python destination dir found: /usr/local/lib/python3.5/dist-packages
-- Python install dir: /usr/local/lib/python3.5/dist-packages/opencog
-- Using nosetests executable /usr/bin/nosetests3
-- Found Intel TBB
-- 
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Detected ZeroMQ version number: 4.1.4
-- ZeroMQ was found.
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- VALGRIND missing: needed for thread debugging.
CMake Error at opencog/cogserver/server/CMakeLists.txt:57 (INSTALL):
  install TARGETS given target "network" which does not exist in this
  directory.

-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 

Building for Ubuntu 16.04.6 LTS

The following components will be built:
-----------------------------------------------
   CogServer        - CogServer network and job server.
   Cython bindings  - Cython (python) bindings.
   Python tests     - Python bindings nose tests.
   Unit tests       - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   Doxygen          - Code documentation.

-- Configuring incomplete, errors occurred!
See also "/home/scrooge/cogserver/build/CMakeFiles/CMakeOutput.log".
See also "/home/scrooge/cogserver/build/CMakeFiles/CMakeError.log".

**Comment by AlucardNosferatu** [comment]
What dependencies did I lack for building cogserver? Thanks!

**Comment by AlucardNosferatu** [comment]
CMake Error at opencog/cogserver/server/CMakeLists.txt:57 (INSTALL):
install TARGETS given target "network" which does not exist in this directory.
Is this "network" a python or module or some kind of C lib need to be installed beforehand?

**Comment by AlucardNosferatu** [comment]
I found a dir named "network" in "cogserver/opencog/", I guess this dir is what I lack for building, but I dont know where should I copy and paste this dir into...
![Screenshot from 2019-11-16 22-55-06](https://user-images.githubusercontent.com/10172485/68995042-6cc9d400-08c4-11ea-83d9-ba86fa1469e2.png)

**Comment by linas** [comment]
I have no clue why this failed. I believe that pull req #13 fixes this.  Please `git pull` and try again.

(The `git pull` will show zillions of changes; I have one a huge refactoring this morning, removing stale code.)

**Comment by AlucardNosferatu** [comment]
The building is successful, Thx!
